export const offeringsFixture = {
	all: {
		default: {
			serverDescription: 'Default offering',
			annual: {
				identifier: '$rc_annual',
				packageType: 'ANNUAL',
				product: {
					description: '',
					introPrice: {
						cycles: 1,
						periodNumberOfUnits: 1,
						priceString: '$0.00',
						period: 'P1W',
						price: 0,
						periodUnit: 'WEEK',
					},
					intro_price: 0,
					intro_price_period_unit: 'WEEK',
					currency_code: 'USD',
					price: 39.9900016784668,
					title: '',
					intro_price_period: 'P1W',
					price_string: '$39.99',
					intro_price_cycles: 1,
					identifier: 'shift_3999_1y_1w_0',
					intro_price_period_number_of_units: 1,
					intro_price_string: '$0.00',
					discounts: [],
				},
				offeringIdentifier: 'default',
			},
			availablePackages: [
				{
					identifier: '$rc_monthly',
					packageType: 'MONTHLY',
					product: {
						description: '',
						introPrice: null,
						intro_price: null,
						intro_price_period_unit: null,
						currency_code: 'USD',
						price: 4.989999771118164,
						title: '',
						intro_price_period: null,
						price_string: '$4.99',
						intro_price_cycles: null,
						identifier: 'shift_499_1m',
						intro_price_period_number_of_units: null,
						intro_price_string: null,
						discounts: [],
					},
					offeringIdentifier: 'default',
				},
				{
					identifier: '$rc_annual',
					packageType: 'ANNUAL',
					product: {
						description: '',
						introPrice: {
							cycles: 1,
							periodNumberOfUnits: 1,
							priceString: '$0.00',
							period: 'P1W',
							price: 0,
							periodUnit: 'WEEK',
						},
						intro_price: 0,
						intro_price_period_unit: 'WEEK',
						currency_code: 'USD',
						price: 39.9900016784668,
						title: '',
						intro_price_period: 'P1W',
						price_string: '$39.99',
						intro_price_cycles: 1,
						identifier: 'shift_3999_1y_1w_0',
						intro_price_period_number_of_units: 1,
						intro_price_string: '$0.00',
						discounts: [],
					},
					offeringIdentifier: 'default',
				},
			],
			identifier: 'default',
			monthly: {
				identifier: '$rc_monthly',
				packageType: 'MONTHLY',
				product: {
					description: '',
					introPrice: null,
					intro_price: null,
					intro_price_period_unit: null,
					currency_code: 'USD',
					price: 4.989999771118164,
					title: '',
					intro_price_period: null,
					price_string: '$4.99',
					intro_price_cycles: null,
					identifier: 'shift_499_1m',
					intro_price_period_number_of_units: null,
					intro_price_string: null,
					discounts: [],
				},
				offeringIdentifier: 'default',
			},
		},
	},
	current: {
		monthly: {
			offeringIdentifier: 'default',
			product: {
				discounts: [],
				intro_price_string: null,
				intro_price_period_number_of_units: null,
				identifier: 'shift_499_1m',
				intro_price_cycles: null,
				price_string: '$4.99',
				intro_price_period: null,
				title: '',
				price: 4.989999771118164,
				currency_code: 'USD',
				intro_price_period_unit: null,
				intro_price: null,
				introPrice: null,
				description: '',
			},
			packageType: 'MONTHLY',
			identifier: '$rc_monthly',
		},
		identifier: 'default',
		availablePackages: [
			{
				offeringIdentifier: 'default',
				product: {
					discounts: [],
					intro_price_string: null,
					intro_price_period_number_of_units: null,
					identifier: 'shift_499_1m',
					intro_price_cycles: null,
					price_string: '$4.99',
					intro_price_period: null,
					title: '',
					price: 4.989999771118164,
					currency_code: 'USD',
					intro_price_period_unit: null,
					intro_price: null,
					introPrice: null,
					description: '',
				},
				packageType: 'MONTHLY',
				identifier: '$rc_monthly',
			},
			{
				offeringIdentifier: 'default',
				product: {
					discounts: [],
					intro_price_string: '$0.00',
					intro_price_period_number_of_units: 1,
					identifier: 'shift_3999_1y_1w_0',
					intro_price_cycles: 1,
					price_string: '$39.99',
					intro_price_period: 'P1W',
					title: '',
					price: 39.9900016784668,
					currency_code: 'USD',
					intro_price_period_unit: 'WEEK',
					intro_price: 0,
					introPrice: {
						periodUnit: 'WEEK',
						price: 0,
						period: 'P1W',
						priceString: '$0.00',
						periodNumberOfUnits: 1,
						cycles: 1,
					},
					description: '',
				},
				packageType: 'ANNUAL',
				identifier: '$rc_annual',
			},
		],
		annual: {
			offeringIdentifier: 'default',
			product: {
				discounts: [],
				intro_price_string: '$0.00',
				intro_price_period_number_of_units: 1,
				identifier: 'shift_3999_1y_1w_0',
				intro_price_cycles: 1,
				price_string: '$39.99',
				intro_price_period: 'P1W',
				title: '',
				price: 39.9900016784668,
				currency_code: 'USD',
				intro_price_period_unit: 'WEEK',
				intro_price: 0,
				introPrice: {
					periodUnit: 'WEEK',
					price: 0,
					period: 'P1W',
					priceString: '$0.00',
					periodNumberOfUnits: 1,
					cycles: 1,
				},
				description: '',
			},
			packageType: 'ANNUAL',
			identifier: '$rc_annual',
		},
		serverDescription: 'Default offering',
	},
}
